app = "blipair-webrtc"
primary_region = "ord"  # Chicago region

[build]
  image = "node:18"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  method = "get"
  path = "/health"
