# fly.toml app configuration file generated for blipair-webrtc on 2025-05-13T20:08:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blipair-webrtc'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
